/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'difficulty' : IDL.Text,
  'examples' : IDL.Vec(IDL.Text),
  'topicId' : IDL.Text,
});
export const OverallStats = IDL.Record({
  'totalCompleted' : IDL.Nat,
  'topicsStarted' : IDL.Nat,
  'totalQuizzesTaken' : IDL.Nat,
  'averageScore' : IDL.Float64,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : IDL.Text,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'topicId' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'difficulty' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'topicId' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'availableDifficulties' : IDL.Vec(IDL.Text),
});
export const UserProgress = IDL.Record({
  'difficulty' : IDL.Text,
  'completed' : IDL.Bool,
  'bestScore' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'quizzesTaken' : IDL.Nat,
  'topicId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLessonContent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Lesson)],
      ['query'],
    ),
  'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
  'getQuestions' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getUserProgress' : IDL.Func([], [IDL.Vec(UserProgress)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitQuizResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [QuizResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'difficulty' : IDL.Text,
    'examples' : IDL.Vec(IDL.Text),
    'topicId' : IDL.Text,
  });
  const OverallStats = IDL.Record({
    'totalCompleted' : IDL.Nat,
    'topicsStarted' : IDL.Nat,
    'totalQuizzesTaken' : IDL.Nat,
    'averageScore' : IDL.Float64,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : IDL.Text,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'topicId' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'difficulty' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'topicId' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'availableDifficulties' : IDL.Vec(IDL.Text),
  });
  const UserProgress = IDL.Record({
    'difficulty' : IDL.Text,
    'completed' : IDL.Bool,
    'bestScore' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'quizzesTaken' : IDL.Nat,
    'topicId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLessonContent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Lesson)],
        ['query'],
      ),
    'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
    'getQuestions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getUserProgress' : IDL.Func([], [IDL.Vec(UserProgress)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitQuizResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [QuizResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };